config/routes.rb
Rails.application.routes.draw do

  resources :locations do
    get :expired, on: :member
  end
  root 'locations#new'

  resources :users, only: [:create, :update]

  mount ActionCable.server => "/cable"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
  attr_accessor :expires_in_mins

  belongs_to :user

  before_create :set_expires_at
  after_update :broadcast_lat_lng

  scope :current, -> { where("locations.expires_at > ?", Time.zone.now) }

  validates :expires_in_mins, presence: true, numericality: true, on: :create

  MIN_SHARING_TIME = 10.minutes

  def expires_in_seconds
    expires_at - Time.zone.now
  end

  def expired?
    expires_at < Time.zone.now
  end

  def set_expires_at
    self.expires_in_mins ||= MIN_SHARING_TIME
    self.expires_at = (Time.zone.now + expires_in_mins.to_i.minutes)
  end

  def broadcast_lat_lng
    return if expired?
    ActionCable.server.broadcast "location_#{id}", { lat: lat, lng: lng }
  end
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :lat, :lng

  has_many :locations

  after_update :update_locations

  def update_locations
    return unless lat.present? && lng.present?

    locations.current.each do |location|
      location.update_attributes(lat: lat, lng: lng)
    end
  end

  def self.build(params)
    User.create!(client: params[:client], token: SecureRandom.uuid)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :set_user_token_in_session
  before_action :detect_browser

  helper_method :current_user, :logged_in?

  def set_user_token_in_session
    if params["userToken"].present?
      if user = User.where(token: params["userToken"]).first
        session[:user_id] = user.id
      end
    end
  end

  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  private

  def detect_browser
    request.variant = :android if request.user_agent =~ /Android/i
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]
  protect_from_forgery except: [:update]

  # GET /locations
  # GET /locations.json
  def index
    render nothing: true, status: :unauthorized unless current_user

    @locations = current_user.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    render :expired if @location.expired?
  end

  def expired; end

  # GET /locations/new
  def new
    @location = Location.new(expires_in_mins: 60)
  end

  # GET /locations/1/edit
  def edit; end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)
    @location.user_id = session[:user_id]

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        ActionCable.server.broadcast \
          "location_#{@location.id}", { lat: @location.lat, lng: @location.lng }
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:name, :expires_in_mins, :lat, :lng)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    # binding.pry
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  protect_from_forgery except: [:create, :update]

  # POST /locations
  # POST /locations.json
  def create
    @user = User.build(user_create_params)

    respond_to do |format|
      if @user.save
        format.json { render json: @user, status: :created }
      else
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update(user_update_params)
        format.json { render json: @user, status: :ok }
      else
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private

    def user_create_params
      params.require(:user).permit(:client)
    end

    def user_update_params
      params.require(:user).permit(:lat, :lng)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reach - Location Sharing</title>
    <link rel="stylesheet" type="text/css" href="https://cloud.typography.com/7268692/635568/css/fonts.css" />

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>

    <% if request.variant.include? :android %>
      <%= stylesheet_link_tag 'ratchet-theme-android', 'data-turbolinks-track': 'reload' %>
    <% else %>
      <%= stylesheet_link_tag 'ratchet-theme-ios', 'data-turbolinks-track': 'reload' %>
    <% end %>
    <meta name="viewport" content="width=device-width, initial-scale=2.0, maximum-scale=1.0, user-scalable=no" />
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="turbolinks-cache-control" content="no-cache">
    <%= yield(:head) %>
  </head>
  <body>
    <div id="content">
      <div id="toolbar" class="sidebar">
        <div class="top-menu">
          <h1>&nbsp;</h1>
        </div>

        <div class="top-title">
          <h1><a href="/">REACH</a></h1>
        </div>

        <div class="top-name">
          <h1><%= yield(:title) %></h1>
        </div>

        <%= yield(:side_menu) %>
      </div>

      <% if content_for(:map_content) %>
        <%= yield(:map_content) %>
      <% end %>

      <div class="wrapper">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/locations/_form.html.erb
<%= form_with(model: location, remote: true) do |form| %>
  <% if location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, 'Name (optional)' %>
    <%= form.text_field :name, id: :location_name %>
  </div>

  <div class="field">
    <%= form.label :expires_in_mins, 'Automatically stop sharing your location in:' %>
    <%= form.select :expires_in_mins, id: :location_expires_in_mins do %>
      <% [['10 minutes', 10], ['20 minutes', 20], ['30 minutes', 30],
          ['45 minutes', 45], ['1 hour', 60], ['2 hours', 120], ['6 hours', 360]].each do |c| -%>
        <%= content_tag(:option, c.first, value: c.last, selected: c.last == @location.expires_in_mins) %>
      <% end %>
    <% end %>
  </div>

  <%= form.submit value: 'Start Sharing', class: 'btn btn-block btn-primary' %>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/expired.html.erb
<% content_for :title do %>
  Expired
<% end %>

<p>
  The location sharing session you've tried to access has expired.
</p>

<% if logged_in? %>
  <%= link_to 'Press here to start a new location sharing session', root_path %>
<% else %>
  <p>
    Download the iPhone or Android application to start sharing your location.
  </p>
<% end %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Locations</h1>

<table>
  <thead>
    <tr>
      <th>Lat</th>
      <th>Lng</th>
      <th>Name</th>
      <th>Expires at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.lat %></td>
        <td><%= location.lng %></td>
        <td><%= location.name %></td>
        <td><%= location.expires_at %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<p>
  Reach lets you share your current location in real time via a URL.
</p>

<% if logged_in? %>
  <%= render 'form', location: @location %>
<% else %>
  <p id='use-app-notice' style='display:none;'>
    Download the iPhone or Android app to share your location
  </p>
<% end %>

<% if logged_in? && !current_user.locations.current.empty? %>
  <br />
  <h2>You are currently sharing</h2>

  <ul class="table-view">
    <% current_user.locations.current.each do |location| %>
      <li class="table-view-cell">
        <%= link_to(location.name.present? ? location.name : '<em>unnamed</em>'.html_safe, location_url(location), class: 'navigate-right') %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/locations/show.html.erb
<% content_for :title do %>
  <%= @location.name %>
<% end %>

<% content_for :side_menu do %>
  <div class="top-join expiry">
    <a>
      <small>EXPIRING IN</small><br />
      <span id="group-countdown">&nbsp;</span>
    </a>
    <script>
      document.addEventListener("turbolinks:load", function() {
        countdownTimer(<%= @location.expires_in_seconds %>, $('#group-countdown'));
      });
    </script>
  </div>
<% end %>

<% if logged_in? %>
  <p id="notice">
    Link copied to clipboard.
  </p>
<% end %>

<div data-location-id="<%= @location.id %>"></div>
<div class="ajax-loader hidden">
  <img src="/assets/ajax-loader.gif" alt="loading animation" />
  <p>Finding Location</p>
</div>

<% content_for(:map_content) do %>
  <div id="map-<%= @location.id %>" class='map' data-lat="<%= @location.lat %>" data-lng="<%= @location.lng %>"></div>
<% end %>

app/views/locations/show.html.old.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lat:</strong>
  <%= @location.lat %>
</p>

<p>
  <strong>Lng:</strong>
  <%= @location.lng %>
</p>

<p>
  <strong>Name:</strong>
  <%= @location.name %>
</p>

<p>
  <strong>Expires at:</strong>
  <%= @location.expires_at %>
</p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>

app/views/pages/home.html.erb
<h1 class="uk-heading-primary">Reach App</h1>

<p>Share your location</p>